import{R as o,q as u,o as M,V as y,j as t,X as j,_ as b}from"./D1zPwdc9cyvUD_PRY_dc.js";import{u as E}from"./DMCex30FeWvvThtDj-pY.js";import{u as C}from"./DEKrkfWNVpi_Q5QzvrSJ.js";import{P as S}from"./BX1oSRh0ebMIVoJEw7K3.js";import{H as A}from"./BqRj4Kh8YikLdguz1juN.js";import{M as G}from"./CWOF9CoeBXrbPDFFFj6o.js";const R=o.createContext(0),w=82,L=u.div`
	flex: 1 1 auto;
	overflow-y: auto;
	display: flex;
	flex-direction: column-reverse;
`,_=u.div`
	margin: 16px 16px 0 16px;
`;function D({guild:i,channel:e}){const n=C(),c=E("MessageList.tsx"),[g,r]=o.useState(!0),[l,d]=o.useState(!1),a=e.messages.groups,f=o.useRef(null),{width:p}=y({ref:f});o.useEffect(()=>{const s=S.getPermission(n.account.id,i,e);d(s.has("READ_MESSAGE_HISTORY"))},[i,e]),o.useEffect(()=>{l&&i&&e&&e.messages.count===0&&e.getMessages(n,!0).then(s=>{r(s===50)})},[i,e,l]);const x=o.useCallback(()=>{if(!e.messages.count)return;const s=a[a.length-1];if(!s){c.warn("No last group found, aborting fetchMore");return}if("status"in s.messages[0])return;const m=s.messages[0].id;c.debug(`Fetching 50 messages before ${m} for channel ${e.id}`),e.getMessages(n,!1,50,m).then(v=>{r(v===50)})},[e,a,r]),h=o.useCallback(s=>t.jsx(G,{group:s},`messageGroup-${s.messages[s.messages.length-1].id}`),[]);return t.jsx(R.Provider,{value:(p??0)-w,children:t.jsx(L,{id:"scrollable-div",ref:f,children:l?t.jsx(j,{dataLength:a.length,next:x,style:{display:"flex",flexDirection:"column-reverse",marginBottom:30,overflow:"hidden"},hasMore:g,inverse:!0,loader:t.jsx(b,{style:{display:"flex",justifyContent:"center",alignContent:"center",marginBottom:30},color:"var(--primary)"}),scrollableTarget:"scrollable-div",endMessage:t.jsxs(_,{children:[t.jsxs("h1",{style:{fontWeight:700,margin:"8px 0"},children:["Welcome to #",e.name,"!"]}),t.jsxs("p",{style:{color:"var(--text-secondary)"},children:["This is the start of the #",e.name," channel."]}),t.jsx(A,{})]}),children:a.map(s=>h(s))}):t.jsx("div",{style:{marginBottom:30,paddingLeft:20,color:"var(--text-secondary)"},children:"You do not have permission to read the history of this channel."})})})}const V=M(D);export{V as M,R as a,w as b};
//# sourceMappingURL=DUOUmxYXG1vvQwxexk_U.js.map
